### ISSUE TITLE
Molecule

### ISSUE THREAD

**Issue by ohdearaugustin** [mgit-at/ansible-collection-roles#50]
With molecule version 6.0.3 the delegate driver is not working anymore.

```
$ molecule test
CRITICAL Failed to find driver delegated. Please ensure that the driver is correctly installed.
```

This is caused by a breaking change.
The delegated driver was renamed to default.

**Comment by MarkusTeufelberger** [comment]
Yay, patch version breaking changes and not even mentioned in their changelog... (https://github.com/ansible/molecule/releases). :roll_eyes:

**Comment by ohdearaugustin** [comment]
Release candidate breaking changes. 
If you take a look at: https://github.com/ansible/molecule/releases/tag/v6.0.0-rc
And there #3960
